# Site
repository: rjn01/rjn01.github.io 
favicon: images/favicon.ico

# Personal info
name: Rajan Puri
title: IT intern at Nestle India Ltd.
email: rajanpuri.07@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: RJN_01
github_username: rjn01
instagram_username: rajan_puri20
linkedin_username: -rajan-puri

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
 Hi, My name's Rajan and I'm a Data Science Enthusiast, currently working as intern at Nestle India Ltd.
 
 I have experience in <mark>Data Science</mark> and <mark>Machine Learning</mark>/<mark>Deep Learning</mark> with some basic knowledge in making web apps.
 
 I speak native <mark>Hindi</mark>, fluent <mark>English</mark>.

 I am most skilled in: <mark>Python</mark> , <mark>Machine Learning</mark> and <mark>Deep Learning</mark>

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Skills

# Education Section
# educaton_title: Education
 
# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  **Additional Experience**
   - Software engineering virtual experience at JPMorgan Chase & Co.
   - Volunteer in Umeed- A Drop of Hope NGO.
   
   Alongside my interests in Data Science and Machine Learning some of my other interests and hobbies are:
   - Open Source
   - Listening to music
   - Reading
 
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
