# Site
repository: rjn01/rjn01.github.io 
favicon: images/favicon.ico

# Personal info
name: Rajan Puri
title: Senior Software Engineer
email: rajanpuri.07@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: RJN_01
github_username: rjn01
instagram_username: __rjn01
linkedin_username: -rajan-puri

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | 
  Driven Senior Software Engineer with a strong commitment to leveraging technology to propel innovation and efficiency. 
  Presently, I am at the forefront of implementing the Retail Loan Origination System (RLOS) for a Bank, where I am optimizing loan processes to elevate the overall customer experience. 
  My career journey has been marked by a track record of leading cross-functional teams and delivering impactful projects within stringent timelines. 
  Proficient in Java, Python, and SQL, I possess hands-on experience in diverse domains including machine learning, deep learning, and web development.

  With a keen eye for detail and a penchant for problem-solving, I excel in navigating complex challenges and crafting robust solutions. 
  My tenure as a Senior Software Engineer at Newgen Software has equipped me with invaluable insights into implementing RLOS solutions for financial institutions across East Africa. 
  Notably, I led the successful delivery of the RLOS project for Equity Bank Kenya, streamlining the loan origination process and significantly reducing time-to-approval through the implementation of innovative features.

  In addition to my software engineering expertise, I am deeply passionate about exploring the realms of data science and machine learning. 
  My journey includes hands-on experience in analyzing data, developing machine learning models, and contributing to open-source projects aimed at advancing the field. 
  Furthermore, I hold certifications in Machine Learning from esteemed institutions such as Stanford University and AWS, underscoring my commitment to continuous learning and professional development.

  As I continue to expand my horizons in the technology landscape, I am eager to explore opportunities that allow me to leverage my skills and expertise to drive meaningful impact. 
  Whether it's optimizing business processes, harnessing data insights, or pioneering innovative solutions, I am poised to contribute effectively to projects that push the boundaries of what's possible. 
  If you're seeking a dedicated professional with a proven track record of delivering results and a passion for innovation, I invite you to connect with me. 
  Let's collaborate to turn ideas into reality and shape the future of technology together.

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Skills

# Education Section
# education_title: Education  # Fixed typo
 
# More Section
# more_title: A Little More About Me
more_content: | 
  **Additional Experience**
   - Open Source Contributions at LoginRadius, Appwrite, Jupyter, Gatsby, and Hasura.
   - Software engineering virtual experience at JPMorgan Chase & Co.
   - Volunteer in Umeed- A Drop of Hope NGO.
   
   Alongside my interests in Data Science and Machine Learning some of my other interests and hobbies are:
   - Open Source
   - Listening to music
   - Reading
 
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
