# Site
repository: rjn01/rjn01.github.io 
favicon: images/favicon.ico

# Personal info
name: Rajan Puri
title: Senior Software Engineer
email: purirajan98@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: RJN_01
github_username: rjn01
instagram_username: __rjn01
linkedin_username: -rajan-puri

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | 
  I am a driven Master's student at Freie Universität Berlin, specializing in Data Science. With a strong background as a Senior Software Engineer, I am dedicated to leveraging technology to enhance efficiency and improve customer experiences.
  In my previous role, I played a pivotal part in implementing the Retail Loan Origination System (RLOS) for a bank, where I optimized loan processes and led cross-functional teams to deliver impactful projects on time. My proficiency in Java, Python, and SQL, along with hands-on experience in machine learning and web development, has equipped me with a diverse skill set to tackle complex challenges effectively.

# Education Section
# education_title: Education  # Fixed typo


# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Skills
 
# More Section
# more_title: A Little More About Me
more_content: | 
  **Additional Experience**
   - Open Source Contributions at LoginRadius, Appwrite, Jupyter, Gatsby, and Hasura.
   - Software engineering virtual experience at JPMorgan Chase & Co.
   - Volunteer in Umeed- A Drop of Hope NGO.
   
   Alongside my interests in Data Science and Machine Learning some of my other interests and hobbies are:
   - Open Source
   - Listening to music
   - Reading
 
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
